name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: Set assembly version to major semver
        run: echo "ASSEMBLY_VERSION=$(echo ${GITHUB_REF:10} | cut -d '.' -f 1).0.0" >> $GITHUB_ENV
      - name: Print assembly version
        run: echo $ASSEMBLY_VERSION
      - name: Pack nupkg
        run: dotnet pack -p:PackageVersion=$RELEASE_VERSION -p:AssemblyVersion=$ASSEMBLY_VERSION --configuration Release --no-build --output digdir/packed Difi.Oppslagstjeneste.Klient
      - name: Pack nupkg
        run: dotnet pack -p:PackageVersion=$RELEASE_VERSION -p:AssemblyVersion=$ASSEMBLY_VERSION --configuration Release --no-build --output digdir/packed Difi.Oppslagstjeneste.Klient.Domene
      - name: Pack nupkg
        run: dotnet pack -p:PackageVersion=$RELEASE_VERSION -p:AssemblyVersion=$ASSEMBLY_VERSION --configuration Release --no-build --output digdir/packed Difi.Oppslagstjeneste.Klient.Scripts
      - name: Push Klient to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGETAPIKEY }}
        run: dotnet nuget push "digdir/packed/Difi.Oppslagstjeneste.Klient.$RELEASE_VERSION.nupkg" --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
      - name: Push Domene to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGETAPIKEY }}
        run: dotnet nuget push "digdir/packed/Difi.Oppslagstjeneste.Klient.Domene.$RELEASE_VERSION.nupkg" --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
      - name: Push Scripts to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGETAPIKEY }}
        run: dotnet nuget push "digdir/packed/Difi.Oppslagstjeneste.Klient.Scripts.$RELEASE_VERSION.nupkg" --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
